-- ═══════════════════════════════════════════════════════════════════════════
-- SEED: 15 test profiles (EN + ZH translations) for testing
-- Run in Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO public.profiles (
    id, name, email, gender, dob, region, city,
    about, gives, wants,
    about_zh, gives_zh, wants_zh,
    balance, wechat, whatsapp, languages,
    tags, subscription_status, coffee_credits,
    avatar_url, created_at, updated_at
) VALUES

('33333333-0000-0000-0000-000000000001',
 'Alex Petrov', 'alex.p@test.com', 'male', '1990-03-15', 'Other', 'Moscow',
 'Serial entrepreneur from Moscow, now based remotely. Built 3 startups in e-commerce and SaaS.',
 'Startup mentorship, fundraising advice, product strategy for early-stage companies.',
 'Co-founders, investors in Asia, business partners for expansion into HK market.',
 '来自莫斯科的连续创业者，目前远程工作。在电商和SaaS领域创立了3家公司。',
 '创业指导、融资建议、早期公司产品战略。',
 '联合创始人、亚洲投资者、拓展香港市场的商业伙伴。',
 '50_50', '', '+79161001001', ARRAY['EN','RU'],
 '["Startup","Entrepreneur","SaaS","Fundraising","E-commerce"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=301', NOW(), NOW()),

('33333333-0000-0000-0000-000000000002',
 'Maria Sokolova', 'maria.s@test.com', 'female', '1992-07-22', 'Other', 'Dubai',
 'Marketing director with 8 years in luxury brands. Worked with Chanel and LVMH in Europe and Middle East.',
 'Brand strategy, luxury marketing, influencer network in Europe and UAE.',
 'Fashion tech founders, retail expansion into Asia, creative collaborators.',
 '拥有8年奢侈品牌经验的营销总监，曾与香奈儿和LVMH合作。',
 '品牌战略、奢侈品营销、欧洲和阿联酋的网红资源。',
 '时尚科技创始人、亚洲零售扩张、创意合作者。',
 '70_30', '', '+971501002002', ARRAY['EN','RU'],
 '["Marketing","Luxury","Branding","Fashion","LVMH"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=302', NOW(), NOW()),

('33333333-0000-0000-0000-000000000003',
 'Dmitry Volkov', 'dmitry.v@test.com', 'male', '1985-11-08', 'Other', 'Singapore',
 'Blockchain developer and Web3 consultant. 6 years building DeFi protocols and NFT platforms.',
 'Smart contract audits, Web3 architecture, crypto tokenomics consulting.',
 'Web3 investors, crypto project founders, legal experts in digital assets.',
 '区块链开发者和Web3顾问，6年DeFi协议和NFT平台开发经验。',
 '智能合约审计、Web3架构、加密经济学咨询。',
 'Web3投资者、加密项目创始人、数字资产法律专家。',
 '30_70', 'dmitryvolkov_wx', '+6591003003', ARRAY['EN','RU'],
 '["Blockchain","Web3","DeFi","NFT","Crypto"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=303', NOW(), NOW()),

('33333333-0000-0000-0000-000000000004',
 'Natasha Kim', 'natasha.k@test.com', 'female', '1994-04-30', 'Other', 'Seoul',
 'UX designer specializing in fintech and healthcare apps. Previously at Kakao and Naver.',
 'UX research, product design, user testing, design system creation.',
 'Product managers, startup CTOs, design-driven founders in Asia.',
 '专注于金融科技和医疗应用的UX设计师，曾就职于Kakao和Naver。',
 'UX研究、产品设计、用户测试、设计系统搭建。',
 '产品经理、初创公司CTO、亚洲设计驱动型创始人。',
 '50_50', '', '+821091004004', ARRAY['EN','RU'],
 '["UX","Design","Fintech","Healthcare","Product"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=304', NOW(), NOW()),

('33333333-0000-0000-0000-000000000005',
 'Igor Morozov', 'igor.m@test.com', 'male', '1988-09-17', 'Other', 'Berlin',
 'AI/ML engineer at a Berlin-based autonomous driving startup. PhD in Computer Vision.',
 'Machine learning consulting, computer vision solutions, AI product development.',
 'AI startup founders, robotics investors, research collaboration opportunities.',
 '柏林自动驾驶初创公司的AI/ML工程师，计算机视觉博士。',
 '机器学习咨询、计算机视觉解决方案、AI产品开发。',
 'AI初创公司创始人、机器人投资者、科研合作机会。',
 '30_70', '', '+4917691005005', ARRAY['EN','RU'],
 '["AI","Machine Learning","Computer Vision","Robotics","PhD"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=305', NOW(), NOW()),

('33333333-0000-0000-0000-000000000006',
 'Elena Novak', 'elena.n@test.com', 'female', '1991-01-25', 'Other', 'Amsterdam',
 'Sustainability consultant helping companies achieve ESG goals. Former Greenpeace campaigner.',
 'ESG strategy, carbon footprint analysis, green certification guidance.',
 'Impact investors, green tech founders, corporate sustainability officers.',
 '帮助企业实现ESG目标的可持续发展顾问，前绿色和平活动人士。',
 'ESG战略、碳足迹分析、绿色认证指导。',
 '影响力投资者、绿色科技创始人、企业可持续发展官员。',
 '70_30', '', '+31621006006', ARRAY['EN','RU'],
 '["ESG","Sustainability","Green Tech","Impact","Carbon"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=306', NOW(), NOW()),

('33333333-0000-0000-0000-000000000007',
 'Pavel Kozlov', 'pavel.k@test.com', 'male', '1987-06-12', 'Other', 'Toronto',
 'Real estate developer focused on PropTech. Built 500+ units across Canada and Eastern Europe.',
 'Real estate investment advice, PropTech connections, development project management.',
 'Asian real estate investors, PropTech startups, construction tech innovators.',
 '专注于房产科技的房地产开发商，在加拿大和东欧建造了500多套住宅。',
 '房地产投资建议、PropTech人脉、开发项目管理。',
 '亚洲房地产投资者、PropTech初创公司、建筑科技创新者。',
 '50_50', '', '+14161007007', ARRAY['EN','RU'],
 '["Real Estate","PropTech","Investment","Development","Canada"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=307', NOW(), NOW()),

('33333333-0000-0000-0000-000000000008',
 'Oksana Shevchenko', 'oksana.s@test.com', 'female', '1993-12-05', 'Other', 'Warsaw',
 'EdTech founder running an online language learning platform with 50k users across Europe.',
 'EdTech product insights, language learning methodology, European market entry.',
 'Asian EdTech investors, content creators, B2B education partnerships.',
 '教育科技创始人，运营一个拥有5万欧洲用户的在线语言学习平台。',
 '教育科技产品洞察、语言学习方法论、欧洲市场进入策略。',
 '亚洲教育科技投资者、内容创作者、B2B教育合作伙伴。',
 '70_30', '', '+48501008008', ARRAY['EN','RU'],
 '["EdTech","Education","Language Learning","Startup","Europe"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=308', NOW(), NOW()),

('33333333-0000-0000-0000-000000000009',
 'Andrei Popescu', 'andrei.p@test.com', 'male', '1989-08-20', 'Other', 'Bucharest',
 'Cybersecurity expert specializing in enterprise security for banks and telecom companies.',
 'Security audits, GDPR compliance, incident response planning.',
 'Fintech CISOs, banking tech investors, cybersecurity product companies.',
 '专注于银行和电信企业安全的网络安全专家。',
 '安全审计、GDPR合规、事件响应规划。',
 '金融科技CISO、银行科技投资者、网络安全产品公司。',
 '30_70', '', '+40721009009', ARRAY['EN','RU'],
 '["Cybersecurity","GDPR","Banking","Telecom","Enterprise"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=309', NOW(), NOW()),

('33333333-0000-0000-0000-000000000010',
 'Svetlana Ivanova', 'svetlana.i@test.com', 'female', '1995-02-14', 'Other', 'Tbilisi',
 'Growth hacker and digital marketing specialist. Scaled 5 startups from 0 to 1M users.',
 'Growth strategy, paid acquisition, viral marketing, community building.',
 'Startup founders needing growth, VC-backed companies, marketing tech tools.',
 '增长黑客和数字营销专家，将5家初创公司从0扩展到100万用户。',
 '增长战略、付费获客、病毒式营销、社区建设。',
 '需要增长的初创公司创始人、VC支持的公司、营销科技工具。',
 '50_50', '', '+99551010010', ARRAY['EN','RU'],
 '["Growth","Marketing","Viral","Community","Startup"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=310', NOW(), NOW()),

('33333333-0000-0000-0000-000000000011',
 'Mikhail Fedorov', 'mikhail.f@test.com', 'male', '1984-10-30', 'Other', 'Almaty',
 'Venture capitalist managing a $50M fund focused on Central Asian and Eastern European startups.',
 'Seed and Series A funding, portfolio company introductions, investor network.',
 'Promising startups in AI, fintech, and marketplace sectors seeking investment.',
 '管理5000万美元基金的风险投资人，专注于中亚和东欧初创公司。',
 '种子轮和A轮融资、投资组合公司介绍、投资者网络。',
 '寻求投资的AI、金融科技和市场领域优质初创公司。',
 '30_70', '', '+77011011011', ARRAY['EN','RU'],
 '["VC","Investment","Fintech","AI","Central Asia"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=311', NOW(), NOW()),

('33333333-0000-0000-0000-000000000012',
 'Anna Belova', 'anna.b@test.com', 'female', '1992-05-18', 'Other', 'Prague',
 'Healthcare startup founder building AI diagnostics for rare diseases. Medical doctor turned entrepreneur.',
 'Medical expertise, healthcare startup insights, clinical trial connections.',
 'MedTech investors, hospital partnerships, AI engineers for healthcare.',
 '医疗初创公司创始人，正在开发罕见病AI诊断系统，由医生转型为创业者。',
 '医学专业知识、医疗初创公司洞察、临床试验资源。',
 '医疗科技投资者、医院合作伙伴、医疗AI工程师。',
 '70_30', '', '+42060112012', ARRAY['EN','RU'],
 '["HealthTech","AI","Medical","Diagnostics","MedTech"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=312', NOW(), NOW()),

('33333333-0000-0000-0000-000000000013',
 'Sergei Lebedev', 'sergei.l@test.com', 'male', '1986-07-07', 'Other', 'Lisbon',
 'Full-stack developer and CTO of a B2B SaaS company serving 200+ enterprise clients in Europe.',
 'Technical architecture advice, CTO mentorship, software development best practices.',
 'Business co-founders, enterprise sales experts, SaaS investors.',
 '全栈开发者，服务欧洲200多家企业客户的B2B SaaS公司CTO。',
 '技术架构建议、CTO导师指导、软件开发最佳实践。',
 '商业联合创始人、企业销售专家、SaaS投资者。',
 '50_50', '', '+35191013013', ARRAY['EN','RU'],
 '["CTO","SaaS","B2B","Enterprise","Full-Stack"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=313', NOW(), NOW()),

('33333333-0000-0000-0000-000000000014',
 'Yulia Romanova', 'yulia.r@test.com', 'female', '1990-11-22', 'Other', 'Barcelona',
 'Fashion designer and sustainable clothing brand founder. Featured in Vogue and Elle.',
 'Fashion industry connections, sustainable manufacturing contacts, brand building.',
 'Retail investors, e-commerce platforms, sustainability-focused fashion partners.',
 '时装设计师和可持续服装品牌创始人，曾登上《Vogue》和《Elle》。',
 '时尚行业人脉、可持续制造商联系、品牌建设。',
 '零售投资者、电商平台、注重可持续发展的时尚合作伙伴。',
 '70_30', '', '+34611014014', ARRAY['EN','RU'],
 '["Fashion","Sustainable","Design","Vogue","Brand"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=314', NOW(), NOW()),

('33333333-0000-0000-0000-000000000015',
 'Konstantin Orlov', 'konstantin.o@test.com', 'male', '1983-04-03', 'Other', 'Vienna',
 'Classical musician turned music tech entrepreneur. Built a streaming platform for classical music with 100k subscribers.',
 'Music industry connections, audio tech expertise, classical music community access.',
 'Music tech investors, streaming platform partnerships, content licensing experts.',
 '古典音乐家转型为音乐科技创业者，创建了拥有10万订阅者的古典音乐流媒体平台。',
 '音乐行业人脉、音频技术专长、古典音乐社区资源。',
 '音乐科技投资者、流媒体平台合作伙伴、内容授权专家。',
 '30_70', '', '+43660115015', ARRAY['EN','RU'],
 '["Music","MusicTech","Streaming","Classical","Audio"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=315', NOW(), NOW())

ON CONFLICT (id) DO UPDATE SET
  about = EXCLUDED.about, gives = EXCLUDED.gives, wants = EXCLUDED.wants,
  about_zh = EXCLUDED.about_zh, gives_zh = EXCLUDED.gives_zh, wants_zh = EXCLUDED.wants_zh,
  updated_at = NOW();
