-- ═══════════════════════════════════════════════════════════════════════════
-- SEED: 20 diverse test profiles (various professions, regions, EN+ZH)
-- Run in Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO public.profiles (
    id, name, email, gender, dob, region, city,
    about, gives, wants,
    about_zh, gives_zh, wants_zh,
    balance, wechat, whatsapp, languages,
    tags, subscription_status, coffee_credits,
    avatar_url, created_at, updated_at
) VALUES

('44444444-0000-0000-0000-000000000001',
 'Wei Chen', 'wei.chen@test.com', 'male', '1985-03-10', 'Mainland', 'Shenzhen',
 'Restaurant chain owner with 12 locations across Guangdong. Started from a small noodle shop.',
 'F&B business advice, supplier network in China, restaurant operations.',
 'Investors for expansion, food tech solutions, franchise partners.',
 '广东连锁餐厅老板，拥有12家门店，从一家小面馆起步。',
 '餐饮业务建议、中国供应商网络、餐厅运营经验。',
 '扩张投资者、餐饮科技解决方案、加盟合作伙伴。',
 '50_50', 'weichen_wx', '', ARRAY['ZH','CAN'],
 '["F&B","Restaurant","China","Franchise","Food"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=401', NOW(), NOW()),

('44444444-0000-0000-0000-000000000002',
 'Sarah Lam', 'sarah.lam@test.com', 'female', '1992-06-15', 'Hong Kong', 'Causeway Bay',
 'Interior designer specializing in luxury residential and hotel projects in HK and Macau.',
 'Design consultations, contractor network, material sourcing in Asia.',
 'Property developers, hotel groups, high-net-worth clients.',
 '专注于香港和澳门豪华住宅及酒店项目的室内设计师。',
 '设计咨询、承包商网络、亚洲材料采购。',
 '房地产开发商、酒店集团、高净值客户。',
 '70_30', 'sarahlam_wx', '+85291002002', ARRAY['EN','ZH','CAN'],
 '["Interior Design","Luxury","Hotel","HK","Property"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=402', NOW(), NOW()),

('44444444-0000-0000-0000-000000000003',
 'James Okafor', 'james.ok@test.com', 'male', '1988-11-22', 'Hong Kong', 'Tsim Sha Tsui',
 'Nigerian-born investment banker at a top-tier firm. Specialist in Africa-Asia cross-border deals.',
 'Investment banking expertise, Africa market access, deal structuring.',
 'African entrepreneurs seeking Asian capital, impact investors.',
 '尼日利亚裔投资银行家，专注于非洲-亚洲跨境交易。',
 '投资银行专业知识、非洲市场准入、交易结构设计。',
 '寻求亚洲资本的非洲企业家、影响力投资者。',
 '30_70', '', '+85291003003', ARRAY['EN'],
 '["Investment Banking","Africa","Cross-border","Finance","Deals"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=403', NOW(), NOW()),

('44444444-0000-0000-0000-000000000004',
 'Lin Xiaomei', 'lin.xm@test.com', 'female', '1995-08-30', 'Mainland', 'Guangzhou',
 'Traditional Chinese medicine practitioner and wellness brand founder with 50k followers.',
 'TCM knowledge, wellness product development, Chinese health market insights.',
 'Health tech investors, wellness app developers, export partners.',
 '传统中医从业者和健康品牌创始人，拥有5万粉丝。',
 '中医知识、健康产品开发、中国健康市场洞察。',
 '健康科技投资者、健康应用开发者、出口合作伙伴。',
 '70_30', 'linxiaomei_wx', '', ARRAY['ZH'],
 '["TCM","Wellness","Health","China","Brand"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=404', NOW(), NOW()),

('44444444-0000-0000-0000-000000000005',
 'Tom Bradley', 'tom.b@test.com', 'male', '1979-04-05', 'Hong Kong', 'Mid-Levels',
 'British expat, 20 years in HK. Partner at a law firm specializing in M&A and IPO.',
 'Legal advice on M&A, IPO preparation, corporate governance.',
 'Startups planning IPO, companies doing cross-border acquisitions.',
 '英国人，在香港生活20年。律师事务所合伙人，专注并购和IPO。',
 '并购法律建议、IPO准备、公司治理。',
 '计划IPO的初创公司、跨境收购企业。',
 '30_70', '', '+85291005005', ARRAY['EN'],
 '["Law","M&A","IPO","HK","Corporate"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=405', NOW(), NOW()),

('44444444-0000-0000-0000-000000000006',
 'Priya Sharma', 'priya.s@test.com', 'female', '1991-12-18', 'Hong Kong', 'Wan Chai',
 'Indian-born yoga instructor and mindfulness coach. Runs corporate wellness programs for banks.',
 'Mindfulness training, stress management, corporate wellness programs.',
 'HR directors, wellness startups, meditation app founders.',
 '印度裔瑜伽教练和正念教练，为银行提供企业健康项目。',
 '正念培训、压力管理、企业健康项目。',
 '人力资源总监、健康初创公司、冥想应用创始人。',
 '70_30', '', '+85291006006', ARRAY['EN'],
 '["Yoga","Wellness","Mindfulness","Corporate","HR"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=406', NOW(), NOW()),

('44444444-0000-0000-0000-000000000007',
 'Chan Wai Kit', 'chan.wk@test.com', 'male', '1983-07-14', 'Hong Kong', 'Kowloon',
 'Third-generation jade merchant. Expert in antique jade valuation and authentication.',
 'Jade market knowledge, antique authentication, collector network in Asia.',
 'Art investors, museum curators, luxury goods platforms.',
 '第三代翡翠商人，古董翡翠鉴定和认证专家。',
 '翡翠市场知识、古董鉴定、亚洲收藏家网络。',
 '艺术投资者、博物馆策展人、奢侈品平台。',
 '50_50', 'chanwaikit_wx', '+85291007007', ARRAY['ZH','CAN','EN'],
 '["Jade","Antiques","Art","Luxury","Collector"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=407', NOW(), NOW()),

('44444444-0000-0000-0000-000000000008',
 'Fatima Al-Rashid', 'fatima.ar@test.com', 'female', '1990-02-28', 'Other', 'Dubai',
 'Halal food certification consultant helping Asian brands enter Middle East markets.',
 'Halal certification process, Middle East market entry, food regulations.',
 'Asian food brands, restaurant chains, food tech companies.',
 '清真食品认证顾问，帮助亚洲品牌进入中东市场。',
 '清真认证流程、中东市场准入、食品法规。',
 '亚洲食品品牌、连锁餐厅、食品科技公司。',
 '50_50', '', '+971501008008', ARRAY['EN'],
 '["Halal","Food","Middle East","Certification","Export"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=408', NOW(), NOW()),

('44444444-0000-0000-0000-000000000009',
 'Kevin Ng', 'kevin.ng@test.com', 'male', '1994-09-03', 'Hong Kong', 'Sham Shui Po',
 'Street fashion designer and streetwear brand founder. Collaborated with Nike and New Balance.',
 'Fashion design, streetwear brand building, youth culture marketing.',
 'Retail investors, fashion tech platforms, brand licensing deals.',
 '街头时尚设计师和潮牌创始人，曾与耐克和新百伦合作。',
 '时装设计、潮牌建设、青年文化营销。',
 '零售投资者、时尚科技平台、品牌授权合作。',
 '70_30', 'kevinnghk_wx', '+85291009009', ARRAY['EN','CAN'],
 '["Fashion","Streetwear","Nike","Brand","Youth"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=409', NOW(), NOW()),

('44444444-0000-0000-0000-000000000010',
 'Dr. Zhang Wei', 'zhang.w@test.com', 'male', '1975-05-20', 'Mainland', 'Beijing',
 'Oncologist at Peking Union Medical College. Researching AI-assisted cancer diagnosis.',
 'Medical expertise, clinical research connections, China healthcare system insights.',
 'MedTech investors, AI diagnostics companies, hospital partnerships.',
 '北京协和医学院肿瘤科医生，研究AI辅助癌症诊断。',
 '医学专业知识、临床研究资源、中国医疗体系洞察。',
 '医疗科技投资者、AI诊断公司、医院合作伙伴。',
 '30_70', 'zhangwei_wx', '', ARRAY['ZH','EN'],
 '["Medical","Oncology","AI","Healthcare","Research"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=410', NOW(), NOW()),

('44444444-0000-0000-0000-000000000011',
 'Maria Santos', 'maria.santos@test.com', 'female', '1989-10-11', 'Other', 'Manila',
 'Filipino nurse turned healthcare recruiter. Places medical staff across Asia and Middle East.',
 'Healthcare recruitment, Philippines talent network, medical staffing.',
 'Hospital HR directors, healthcare startups, medical education platforms.',
 '菲律宾护士转型为医疗招聘专员，在亚洲和中东安置医疗人员。',
 '医疗招聘、菲律宾人才网络、医疗人员配置。',
 '医院人力资源总监、医疗初创公司、医学教育平台。',
 '50_50', '', '+63917011011', ARRAY['EN'],
 '["Healthcare","Recruitment","Philippines","Nursing","HR"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=411', NOW(), NOW()),

('44444444-0000-0000-0000-000000000012',
 'Luo Jianming', 'luo.jm@test.com', 'male', '1987-01-25', 'Mainland', 'Shanghai',
 'Solar energy entrepreneur. Built 3 solar farms in Xinjiang and Inner Mongolia.',
 'Renewable energy project development, government relations in China, green financing.',
 'Clean energy investors, carbon credit buyers, international energy companies.',
 '太阳能创业者，在新疆和内蒙古建造了3个太阳能农场。',
 '可再生能源项目开发、中国政府关系、绿色融资。',
 '清洁能源投资者、碳信用买家、国际能源公司。',
 '30_70', 'luojm_wx', '', ARRAY['ZH','EN'],
 '["Solar","Renewable Energy","China","Green","Carbon"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=412', NOW(), NOW()),

('44444444-0000-0000-0000-000000000013',
 'Emma Wilson', 'emma.w@test.com', 'female', '1993-04-07', 'Hong Kong', 'Kennedy Town',
 'Australian expat, food blogger with 200k followers. Runs HK food tours and cooking classes.',
 'Food content creation, HK restaurant connections, culinary tourism.',
 'Restaurant partners, food brands, tourism platforms.',
 '澳大利亚人，拥有20万粉丝的美食博主，经营香港美食游和烹饪课。',
 '美食内容创作、香港餐厅资源、烹饪旅游。',
 '餐厅合作伙伴、食品品牌、旅游平台。',
 '70_30', '', '+85291013013', ARRAY['EN'],
 '["Food","Blogger","HK","Tourism","Cooking"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=413', NOW(), NOW()),

('44444444-0000-0000-0000-000000000014',
 'Huang Ting', 'huang.t@test.com', 'female', '1996-08-19', 'Mainland', 'Chengdu',
 'Live streaming e-commerce host with 2M followers on Douyin. Sells local Sichuan products.',
 'Live commerce expertise, Douyin/TikTok marketing, Sichuan product sourcing.',
 'Brand partnerships, cross-border e-commerce, international market entry.',
 '抖音直播电商主播，拥有200万粉丝，销售四川本地产品。',
 '直播电商专业知识、抖音/TikTok营销、四川产品采购。',
 '品牌合作、跨境电商、国际市场进入。',
 '50_50', 'huangting_wx', '', ARRAY['ZH'],
 '["Live Commerce","Douyin","TikTok","Sichuan","E-commerce"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=414', NOW(), NOW()),

('44444444-0000-0000-0000-000000000015',
 'Robert Kim', 'robert.k@test.com', 'male', '1981-12-03', 'Other', 'Seoul',
 'Korean game developer. Founded a mobile gaming studio with 5M downloads across Asia.',
 'Game development, Asian gaming market insights, mobile monetization.',
 'Gaming investors, publishers, IP licensing partners.',
 '韩国游戏开发者，创立了在亚洲拥有500万下载量的手游工作室。',
 '游戏开发、亚洲游戏市场洞察、移动端变现。',
 '游戏投资者、发行商、IP授权合作伙伴。',
 '50_50', '', '+82101015015', ARRAY['EN'],
 '["Gaming","Mobile","Korea","Asia","IP"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=415', NOW(), NOW()),

('44444444-0000-0000-0000-000000000016',
 'Aisha Diallo', 'aisha.d@test.com', 'female', '1994-03-22', 'Other', 'Nairobi',
 'Kenyan fintech founder building mobile payment solutions for unbanked populations in Africa.',
 'African fintech insights, mobile money expertise, impact investing connections.',
 'Asian investors interested in Africa, payment infrastructure partners.',
 '肯尼亚金融科技创始人，为非洲无银行账户人群开发移动支付解决方案。',
 '非洲金融科技洞察、移动支付专业知识、影响力投资资源。',
 '对非洲感兴趣的亚洲投资者、支付基础设施合作伙伴。',
 '30_70', '', '+254701016016', ARRAY['EN'],
 '["Fintech","Africa","Mobile Payment","Impact","Unbanked"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=416', NOW(), NOW()),

('44444444-0000-0000-0000-000000000017',
 'Ho Siu Wai', 'ho.sw@test.com', 'male', '1970-06-08', 'Hong Kong', 'Sheung Wan',
 'Third-generation shipping company owner. Manages a fleet of 15 cargo vessels in Asia-Pacific.',
 'Shipping logistics, port connections across Asia, cargo insurance expertise.',
 'E-commerce companies needing logistics, port tech startups, trade finance.',
 '第三代航运公司老板，管理亚太地区15艘货船船队。',
 '航运物流、亚洲港口资源、货运保险专业知识。',
 '需要物流的电商公司、港口科技初创公司、贸易融资。',
 '30_70', 'hosiuwai_wx', '+85291017017', ARRAY['CAN','ZH','EN'],
 '["Shipping","Logistics","HK","Cargo","Trade"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=417', NOW(), NOW()),

('44444444-0000-0000-0000-000000000018',
 'Zara Ahmed', 'zara.a@test.com', 'female', '1997-09-14', 'Other', 'London',
 'Pakistani-British fashion influencer and modest fashion brand founder. 500k Instagram followers.',
 'Modest fashion market, Muslim consumer insights, influencer marketing.',
 'Fashion investors, e-commerce platforms, brand collaborations.',
 '巴基斯坦裔英国时尚博主和保守时尚品牌创始人，Instagram拥有50万粉丝。',
 '保守时尚市场、穆斯林消费者洞察、网红营销。',
 '时尚投资者、电商平台、品牌合作。',
 '70_30', '', '+447901018018', ARRAY['EN'],
 '["Fashion","Modest","Muslim","Influencer","Brand"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=418', NOW(), NOW()),

('44444444-0000-0000-0000-000000000019',
 'Tang Guoqiang', 'tang.gq@test.com', 'male', '1968-11-30', 'Mainland', 'Hangzhou',
 'Retired factory owner turned angel investor. Invested in 20+ manufacturing startups.',
 'Manufacturing expertise, angel investment, supply chain optimization.',
 'Hardware startups, manufacturing tech companies, industrial IoT.',
 '退休工厂主转型天使投资人，已投资20多家制造业初创公司。',
 '制造业专业知识、天使投资、供应链优化。',
 '硬件初创公司、制造科技公司、工业物联网。',
 '30_70', 'tanggq_wx', '', ARRAY['ZH'],
 '["Manufacturing","Angel","Investment","Supply Chain","IoT"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=419', NOW(), NOW()),

('44444444-0000-0000-0000-000000000020',
 'Sophie Dubois', 'sophie.d@test.com', 'female', '1986-07-17', 'Hong Kong', 'Repulse Bay',
 'French sommelier and wine importer. Brings premium French and Italian wines to Asia.',
 'Wine expertise, European supplier network, luxury hospitality connections.',
 'Restaurant owners, hotel F&B directors, wine collectors in Asia.',
 '法国侍酒师和葡萄酒进口商，将优质法国和意大利葡萄酒带入亚洲。',
 '葡萄酒专业知识、欧洲供应商网络、豪华酒店资源。',
 '餐厅老板、酒店餐饮总监、亚洲葡萄酒收藏家。',
 '70_30', '', '+85291020020', ARRAY['EN','ZH'],
 '["Wine","Sommelier","France","Luxury","Hospitality"]'::jsonb,
 'active', 3, 'https://picsum.photos/150?random=420', NOW(), NOW())

ON CONFLICT (id) DO UPDATE SET
  about = EXCLUDED.about, gives = EXCLUDED.gives, wants = EXCLUDED.wants,
  about_zh = EXCLUDED.about_zh, gives_zh = EXCLUDED.gives_zh, wants_zh = EXCLUDED.wants_zh,
  updated_at = NOW();
